name: Docker CPU

on:
  workflow_dispatch:
    inputs:
      tag:
        description: TAG of new image
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/koi-kojima/jupyter
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: Tag name chack
        run: echo "$TAG" | grep -q "cpu_cv"
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          push: true
          file: Dockerfile_nobuild
